"""Reuse the original discussion while qualifying unidentifiable mechanisms."""
from pathlib import Path
P=Path(__file__).resolve().parents[1]
s=(P/'source/section_06.md').read_text()
def para(prefix):return next(x for x in s.splitlines() if x.startswith(prefix))
def span(start,end):return s[s.index(start):s.index(end)].strip()
bry='[Brynjolfsson, Chandar e Chen (2025)](https://digitaleconomy.stanford.edu/publication/canaries-in-the-coal-mine-six-facts-about-the-recent-employment-effects-of-artificial-intelligence/)'
hos='[Hosseini Maasoum e Lichtinger (2026)](https://doi.org/10.2139/ssrn.5425555)'
hum='[Humlum e Vestergaard (2026)](https://doi.org/10.3386/w33777)'
uk='[Klein Teeselink (2025)](https://doi.org/10.2139/ssrn.5516798)'
ch='[Chandar (2025)](https://doi.org/10.2139/ssrn.5384519)'
discussion=['# 6 Discussão dos resultados',
'## 6.1 Limites da identificação: pandemia, ciclo e diferenças estruturais',
para('O que vem a seguir são leituras minhas'),
'**REVISAR COM MANÉ — R06: pandemia, ciclo e mensuração da adoção**',
'A rejeição sistemática das tendências paralelas é o fato metodológico central deste trabalho. Duas hipóteses ajudam a organizar a discussão, sem se excluírem: a recuperação da pandemia e a resposta desigual dos grupos ao ciclo econômico. O painel começa em janeiro de 2021 e o pré-tratamento vai até novembro de 2022. Não há um mês pré-pandemia na janela de comparação. O teste examina um mercado em recuperação de um choque que pode ter atingido de forma diferente o trabalho remoto, administrativo e de atendimento, de um lado, e o trabalho manual e presencial, de outro. Se essa recomposição ainda estava em curso em 2022 e 2023, os grupos poderiam seguir trajetórias distintas por razões anteriores ao ChatGPT. O desenho não identifica quanto do diferencial decorre dessa hipótese.',
'As sensibilidades mostram que a janela e a composição importam: iniciando a amostra em janeiro de 2022, o diferencial salarial cai de −0,0507 para −0,0363; interagindo características pré-tratamento com o pós, chega a −0,0360. A decomposição por escolaridade da Seção 5.2 associa cerca de 23% do diferencial à composição dos admitidos. Essas mudanças são compatíveis com diferenças anteriores ao evento, mas não demonstram que a pandemia tenha produzido essa parcela do coeficiente.',
para('O contra-argumento é forte'),
'A hipótese macroeconômica também precisa ser confrontada com o que o grupo tratado é em volume. Das 75 famílias expostas, auxiliares de escritório e assistentes administrativos respondem por 31,8% das admissões prévias, e as cinco maiores somam 65,4%: escritório, atendimento comercial, recepção, telemarketing e vendas. Antes do evento, 19,7% dos admitidos nas ocupações tratadas tinham ensino superior, contra 4,0% no controle; a idade média era 28,9 anos contra 33,8. São populações ocupacionais estruturalmente distintas. Choques de demanda, de crédito ou de investimento podem atingir esses perfis de modo diferente, mesmo com efeitos fixos de mês.',
'Daí vem um problema de identificação: a fronteira desenhada pelo índice de exposição se sobrepõe à fronteira entre trabalho de escritório e atendimento e trabalho manual ou presencial. Um choque tecnológico e um choque de demanda concentrados no primeiro conjunto podem produzir diferenciais parecidos. Os dados desta dissertação não separam suas contribuições. Observar a adoção de IA ajudaria a distinguir exposição potencial de uso efetivo, mas não resolveria sozinho a identificação: firmas escolhem se e quando adotam, e essas escolhas podem acompanhar produtividade, demanda ou expectativas. Seria necessário um desenho que tratasse também essa seleção.',
'O lançamento do ChatGPT é um marco observável, mas a difusão é gradual. A janela de janeiro de 2021 a maio de 2026 combina um pré-período sem comparação pré-pandemia e um pós em que a tecnologia ainda muda. Encurtar a amostra, acrescentar efeitos setoriais ou observar coeficientes estáveis não cria, por si, o contrafactual ausente.',
'## 6.2 Diálogo internacional por achado',
'**REVISAR COM MANÉ — R07: comparação internacional e versões dos estudos**',
'A comparação abaixo usa as versões já citadas e arquivadas: Brynjolfsson, Chandar e Chen, de 13 de novembro de 2025; Hosseini Maasoum e Lichtinger, de 6 de junho de 2026; Humlum e Vestergaard, revisão de março de 2026; Klein Teeselink, de 21 de dezembro de 2025; e Chandar, de 1º de agosto de 2025. A página de Canaries já oferece uma revisão posterior, de agosto de 2026. Fixar a versão deixa claro a quais resultados a comparação se refere, sem misturar atualizações de amostra com os números usados nesta dissertação.',
f'**Emprego médio.** A literatura ainda oferece resultados distintos. Na Dinamarca, {hum} ligam pesquisas de adoção a registros administrativos e encontram efeitos médios nulos e precisos em rendimentos e horas. Nos Estados Unidos, {ch} não encontra evidência de declínio agregado do emprego nas ocupações expostas na CPS até o primeiro trimestre de 2025. Já {uk} encontra reduções de emprego e de vagas no Reino Unido, concentradas nos segmentos de alta remuneração. Aqui, a falta de identificação nos fluxos nacionais impede concluir que haja efeito médio da IA ou que ele seja zero. Fluxos de admissões e desligamentos, estoques de emprego e anúncios de vagas são margens relacionadas, mas distintas.',
f'**Jovens e início de carreira.** {bry} documentam queda relativa de 16% no emprego de trabalhadores de 22–25 anos nas ocupações mais expostas, na versão usada. {hos} encontram redução do emprego júnior em firmas adotantes, principalmente por menor contratação; os desligamentos também caem, em menor magnitude. No Brasil, a maior exposição potencial dos jovens na Seção 3 não coincide com queda adicional clara nas admissões de 22–25 anos. O DDD mais preciso aparece em 41–49 anos e é positivo nos três fluxos. Idade e senioridade não são equivalentes; além disso, as unidades, classificações de exposição e amostras diferem. O contraste brasileiro não demonstra proteção de trabalhadores experientes nem contradiz diretamente os estudos de firmas.',
f'**Salários.** O salário real de admissão é a margem nacional mais precisa desta dissertação, embora sem identificação causal. No estudo de {bry}, o ajuste é mais visível no emprego do que na remuneração-base. {hum} encontram estimativas médias próximas de zero para rendimentos e horas, com intervalos que excluem efeitos superiores a 2%. {uk} também examina salários anunciados nas vagas. Salário de entrada, remuneração dos empregados, rendimentos e salário anunciado não medem o mesmo objeto. A menor precisão de uma margem em outro estudo não valida nem refuta o diferencial brasileiro.',
f'**Pré-tendências e identificação.** Na versão de novembro de 2025, {bry} reconhecem crescimento mais lento desde cerca de 2020 no quintil mais exposto segundo Eloundou e coautores, mas não encontram a mesma divergência anterior com as medidas da Anthropic. Esse ponto está no exercício com amostra mais longa, que recua a 2018. Aqui a falha é mais abrangente e persiste nas alternativas examinadas. Isso reforça a necessidade de ler cada resultado com sua medida de exposição, janela e diagnóstico; não implica que toda a literatura tenha o mesmo problema de identificação.',
'As comparações distributivas também pedem cuidado. A maior exposição de mulheres e de trabalhadores escolarizados é uma afirmação sobre potencial técnico. Os contrastes brasileiros de raça/cor, escolaridade e renda ocupacional são exploratórios e usam complementos próprios. Remuneração ocupacional não equivale a escolaridade ou renda individual, e os resultados para a categoria sem raça/cor identificada não descrevem uma população racial substantiva.',
'## 6.3 Limites das médias, trajetórias e ocupações pequenas',
'**REVISAR COM MANÉ — R08: ocupações pequenas, ponderação e hipóteses sobre trajetórias**',
'Os resultados agregados não estabelecem que haja substituição em curso no mercado formal brasileiro, mas também não demonstram sua ausência. A concentração dos fluxos em poucas ocupações dificulta enxergar mudanças em famílias pequenas por meio de um número agregado. O peso de cada observação na estimação depende do estimador, dos efeitos fixos e da variação observada; não é correto tratar todos os coeficientes como médias ponderadas diretamente pela participação prévia nas admissões.',
para('Tradutores e intérpretes ilustram'),
'Como exercício descritivo de escala, eliminar um volume de admissões equivalente a toda a participação prévia dos tradutores e intérpretes retiraria cerca de 0,041% do total tratado daquele período. Esse cálculo não é uma simulação do coeficiente PPML nem informa quanto ele mudaria. Ele apenas mostra como uma transformação intensa numa ocupação pequena pode ser pouco visível no volume agregado. Investigações sobre ocupações particulares exigem desenhos dedicados.',
para('Uma interpretação possível é que ocupações'),
span('**A estabilidade da trajetória é um diagnóstico','**O gradiente etário é relativo'),
para('Uma hipótese é que experiência'),
'A redução conjunta de admissões e desligamentos também é compatível com a hipótese de acomodação silenciosa, mas os fluxos do CAGED não identificam estabilidade do estoque. No Apêndice D, a RAIS mostra diferencial de estoque formal negativo e diferencial de rotatividade impreciso, sem favorecer essa hipótese. Na PNADc, nenhum dos seis testes de informalidade rejeita e os estoques formal e informal se movem no mesmo sentido. As medições de estoque discordam de sinal e não medem o mesmo objeto; os diagnósticos não permitem escolher uma delas como resposta causal. O proxy de saldo acumulado também não é estoque observado.',
'Esses dados não acompanham a mesma pessoa ao longo do tempo. Uma mudança na composição dos fluxos ou nos estoques não informa para onde foi um trabalhador que deixou uma ocupação exposta. A RAIS disponível acrescenta somente dois anos pós completos, 2023 e 2024, e a PNADc usa cortes transversais repetidos. A extensão espacial do Apêndice B.3 parou no diagnóstico de suporte: retomá-la exigiria variação de capacidade digital menos concentrada entre estados ou outra estratégia de inferência.',
'## 6.4 Aprendizados das escolhas de mensuração',
'**REVISAR COM MANÉ — R09: contribuição e custos da adaptação ocupacional**',
'As duas escolhas estruturais, o índice da OIT e o CAGED, aproximam a pergunta dos dados disponíveis e deixam custos visíveis. O índice da OIT oferece uma medida baseada em tarefas e estruturada na ISCO-08, para a qual existe uma ponte institucional com a CBO. Ele não mede diretamente o conteúdo efetivo das tarefas de cada empresa brasileira nem sua adoção de IA. Um índice construído e validado sobre tarefas brasileiras permitiria investigar particularidades que essa adaptação não capta.',
'A correspondência entre classificações cobra um preço. No universo de 629 famílias do crosswalk, 193 não recebem pontuação e 95 têm exposição mínima; o contraste principal usa 341. No painel observado, a presença adicional da CBO 2414 leva a 630 famílias e 194 sem pontuação. A perda não é aleatória ao longo da estrutura ocupacional. A agregação muitos-para-muitos também reduz granularidade: na CBO 4121, por exemplo, os destinos ISCO têm pontuações 0,43, 0,65 e 0,70. Essa compressão não demonstra que os coeficientes sejam limites inferiores de um efeito verdadeiro.',
'As variantes preservadas no pacote permitem avaliar essas escolhas sem redefini-las a partir do resultado. O coeficiente de exposição contínua padronizada, −0,0188 por desvio-padrão, não deve ser comparado diretamente ao contraste binário −0,0507: mudam a unidade e a amostra, de 341 para 436 famílias. Incorporar exposição mínima ao controle também muda a população de comparação, como mostra a Seção 5.2. Nenhuma dessas alternativas transforma a exposição potencial em adoção observada ou resolve as pré-tendências.',
'O CAGED oferece registro mensal detalhado da porta de entrada e de saída do emprego formal. A PNAD Contínua é mais adequada ao retrato distributivo e à informalidade; a RAIS, ao estoque anual formal. Usar cada base para a margem que observa é uma contribuição do desenho, desde que a análise não confunda fluxo, estoque e transição individual. A adaptação brasileira entrega mensuração e evidência documentada, junto dos limites que um desenho futuro precisará enfrentar.'
]
(P/'sections/06_discussion.md').write_text('\n'.join(discussion)+'\n')

conclusion=[
'Esta dissertação construiu e aplicou uma medida de exposição ocupacional à inteligência artificial para o Brasil e investigou se ocupações mais expostas apresentaram mudanças diferenciais nos fluxos e nos salários do emprego formal após a difusão do ChatGPT. Duas perguntas organizaram o trabalho: quem está mais exposto à IA no país e o que aconteceu com admissões, desligamentos e salários das ocupações formais mais expostas depois de novembro de 2022.',
'A resposta à primeira pergunta é nítida. Entre os 97,8 milhões de trabalhadores retratados no terceiro trimestre de 2025, 10,1% estão em ocupações de alta exposição. Essa exposição se concentra no apoio administrativo, entre mulheres, brancos, jovens e trabalhadores com maior escolaridade. A formalidade reforça o recorte: 14,8% dos formais estão em alta exposição, contra 6,7% dos informais. O mapa mostra que o potencial técnico da IA já se distribui de forma desigual antes de se observar qualquer efeito sobre o emprego.',
'A resposta à segunda pergunta é mais qualificada. No agregado nacional, os diferenciais são negativos e imprecisos nas admissões e nos desligamentos. O salário real de admissão apresenta o padrão mais preciso, com coeficiente de −0,0507, aproximadamente −5,1%. As tendências prévias, porém, falham inclusive nessa margem e nas especificações alternativas examinadas. Esses números descrevem diferenças entre grupos após o evento; não estabelecem que a inteligência artificial as tenha produzido nem demonstram ausência de efeitos.',
'As heterogeneidades acrescentam padrões exploratórios. Os contrastes de fluxo mais negativos aparecem entre trabalhadores negros, sobretudo pardos, enquanto os da faixa de 41–49 anos são positivos em relação ao complemento, sem demonstrar proteção desse grupo. Sexo não apresenta diferença ajustada em admissões, desligamentos ou salário, mas há uma exceção no saldo. Ensino superior fica próximo do limiar ajustado nas duas margens principais e rejeita em fluxo bruto e saldo. O salário da renda ocupacional alta também rejeita após BH, com suporte baixo. As tabelas completas preservam as demais exceções de saldo e a rejeição salarial na categoria sem raça/cor identificada. Pré-tendências, multiplicidade e suporte impedem transformar esse conjunto em um mapa de quem foi afetado pela tecnologia.',
'Quatro blocos de limitações delimitam o alcance do trabalho. Primeiro, exposição potencial não é adoção efetiva. Segundo, a identificação causal não foi alcançada. Terceiro, a análise principal com o CAGED observa fluxos formais e não acompanha trabalhadores; RAIS e PNADc ampliam as margens observadas, mas não identificam transições individuais nem resolvem a comparação causal. Quarto, a mensuração perde informação no crosswalk e a janela iniciada em 2021 não contém um pré-pandemia comparável. A difusão gradual da tecnologia e o horizonte ainda limitado, especialmente os dois anos pós completos da RAIS, acrescentam cautela à leitura.',
'Quatro prioridades decorrem desses limites: medir adoção efetiva de IA por empresas e trabalhadores, com um desenho que enfrente sua seleção; acompanhar trabalhadores ao longo do tempo para observar transições; estender o horizonte para distinguir mudanças persistentes de ajustes iniciais; e melhorar a mensuração ocupacional brasileira, inclusive avaliando correspondências semânticas entre tarefas com validação contra a ponte oficial. Cada caminho amplia o que pode ser observado, mas nenhum dispensa uma estratégia de identificação.',
'A contribuição do trabalho é oferecer uma medida de exposição adaptada ao país, um retrato distributivo de quem está sob ela e evidência documentada sobre a evolução recente do emprego formal mais exposto. Os resultados vêm acompanhados dos diagnósticos que delimitam o que os dados podem e não podem responder. Esse é o ponto de partida que a dissertação deixa: uma base para avançar quando houver mais tempo de observação, melhor mensuração das tarefas e medidas de adoção efetiva.'
]
(P/'sections/07_conclusion.md').write_text('# 7 Conclusão\n**REVISAR COM MANÉ — R10: conclusão completa em sete parágrafos; ênfase e voz**\n'+'\n'.join(conclusion)+'\n')
assert len(conclusion)==7
print('Discussion and seven-paragraph conclusion assembled.')
